---
# tasks file for firewalld
- name: "Install the latest version of Apache - {{firewalld_package_var }}"
  ansible.builtin.dnf:
    name: "{{firewalld_package_var }}"
    state: latest

- name: "Start/Enable service {{ firewalld_service_var }}, if not started/enabled"
  ansible.builtin.service:
    name: "{{ firewalld_service_var }}"
    state: restarted

- name: Enable http port
  ansible.posix.firewalld:
    immediate: yes 
    service: "{{ apache_port }}"
    permanent: yes
    state: enabled


