---
# tasks file for firewalld
- name: Install firewalld package.
  ansible.builtin.dnf:
    name: "{{ firewalld_package }}"
    state: present 

- name: Start and enable firewalld service.
  ansible.builtin.service:
    name: "{{ firewalld_service }}"
    state: started 
    enabled: true 

- name: permit traffic in default zone for http/https service
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes 
  loop: "{{ port_list }}"

