---
- name: Deploy Apache service.
  hosts: prod 
  vars:
    - package_list:
         - httpd
         - firewalld 
    - apache_service: httpd 
    - firewalld_service: firewalld
    - firewalld_rule: http

  tasks:
    - name: "Install required packages - {{ package_list }}"
      ansible.builtin.dnf: 
         name: "{{ package_list }}"
         state: present 

    - name: Start and enable apache service.
      ansible.builtin.service:
         name: "{{ apache_service }}"
         state: started
         enabled: true 

    - name: Start and enable firewalld service.
      ansible.builtin.service:
         name: "{{firewalld_service }}"
         state: started
         enabled: true 

    - name: Adding firewalld rules - http
      ansible.posix.firewalld:
        immediate: yes
        service: "{{ firewalld_rule }}"
        permanent: yes
        state: enabled
 
    - name: Deploy index.html
      ansible.builtin.copy:
         content: "This is my web server {{ inventory_hostname }}\n"
         dest: /var/www/html/index.html
...
