---
- name: Installing packages.
  hosts: localhost 
  tasks:
    - name: Updating all required packages  
      ansible.builtin.dnf: 
            name: "*" 
            state: latest 
      #when: inventory_hostname in groups['dev'] 
...
