- name: Timesync role from collection - redhat.rhel_system_roles
  hosts: prod
  vars:
    timesync_ntp_servers:
      - hostname: 172.25.254.254
        iburst: yes

  roles:
    - redhat.rhel_system_roles.timesync

