---
- name: root account password update.
  hosts: all
  vars_files:
    - mypass.yaml
  tasks:
    - name: root password update.
      ansible.builtin.user:
        name: root
        password: "{{ root_pass | password_hash('sha512') }}"  
        
