---
- name: Install remote facts
  hosts: lb
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
   - name: Create the remote directory
     ansible.builtin.file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
   - name: Install the new facts
     copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}" 

   - name: Verifiy facts 
     ansible.builtin.debug:
       msg: " This is my package-name = {{ansible_facts.ansible_local.custom.general.name }}"

   - name: Verifiy facts 
     ansible.builtin.debug:
       msg: " This is my package-name = {{ansible_facts.ansible_local.custom.general.package }}"


